# coding: utf-8

# flake8: noqa
"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from hs5_api.models.add_access_key_params import AddAccessKeyParams
from hs5_api.models.add_access_key_resp import AddAccessKeyResp
from hs5_api.models.add_bucket_params import AddBucketParams
from hs5_api.models.add_bucket_resp import AddBucketResp
from hs5_api.models.add_policy_params import AddPolicyParams
from hs5_api.models.add_policy_resp import AddPolicyResp
from hs5_api.models.add_role_params import AddRoleParams
from hs5_api.models.add_role_policy_params import AddRolePolicyParams
from hs5_api.models.add_role_policy_resp import AddRolePolicyResp
from hs5_api.models.add_role_resp import AddRoleResp
from hs5_api.models.add_user_params import AddUserParams
from hs5_api.models.add_user_resp import AddUserResp
from hs5_api.models.add_user_role_params import AddUserRoleParams
from hs5_api.models.add_user_role_resp import AddUserRoleResp
from hs5_api.models.change_password_params import ChangePasswordParams
from hs5_api.models.change_password_resp import ChangePasswordResp
from hs5_api.models.change_policy_params import ChangePolicyParams
from hs5_api.models.change_policy_resp import ChangePolicyResp
from hs5_api.models.delete_bucket_params import DeleteBucketParams
from hs5_api.models.delete_bucket_resp import DeleteBucketResp
from hs5_api.models.hapi_error import HapiError
from hs5_api.models.list_access_keys_params import ListAccessKeysParams
from hs5_api.models.list_access_keys_resp import ListAccessKeysResp
from hs5_api.models.list_access_keys_resp_access_keys_inner import ListAccessKeysRespAccessKeysInner
from hs5_api.models.list_params import ListParams
from hs5_api.models.list_policies_params import ListPoliciesParams
from hs5_api.models.list_policies_resp import ListPoliciesResp
from hs5_api.models.list_policies_resp_policies_inner import ListPoliciesRespPoliciesInner
from hs5_api.models.list_resp import ListResp
from hs5_api.models.list_resp_objects_inner import ListRespObjectsInner
from hs5_api.models.list_role_policies_params import ListRolePoliciesParams
from hs5_api.models.list_role_policies_resp import ListRolePoliciesResp
from hs5_api.models.list_role_policies_resp_role_policies_inner import ListRolePoliciesRespRolePoliciesInner
from hs5_api.models.list_roles_params import ListRolesParams
from hs5_api.models.list_roles_resp import ListRolesResp
from hs5_api.models.list_roles_resp_roles_inner import ListRolesRespRolesInner
from hs5_api.models.list_user_roles_params import ListUserRolesParams
from hs5_api.models.list_user_roles_resp import ListUserRolesResp
from hs5_api.models.list_user_roles_resp_user_roles_inner import ListUserRolesRespUserRolesInner
from hs5_api.models.list_users_params import ListUsersParams
from hs5_api.models.list_users_resp import ListUsersResp
from hs5_api.models.list_users_resp_users_inner import ListUsersRespUsersInner
from hs5_api.models.login_params import LoginParams
from hs5_api.models.login_resp import LoginResp
from hs5_api.models.logout_params import LogoutParams
from hs5_api.models.logout_resp import LogoutResp
from hs5_api.models.remove_access_key_params import RemoveAccessKeyParams
from hs5_api.models.remove_access_key_resp import RemoveAccessKeyResp
from hs5_api.models.remove_policy_params import RemovePolicyParams
from hs5_api.models.remove_policy_resp import RemovePolicyResp
from hs5_api.models.remove_role_params import RemoveRoleParams
from hs5_api.models.remove_role_policy_params import RemoveRolePolicyParams
from hs5_api.models.remove_role_policy_resp import RemoveRolePolicyResp
from hs5_api.models.remove_role_resp import RemoveRoleResp
from hs5_api.models.remove_user_params import RemoveUserParams
from hs5_api.models.remove_user_resp import RemoveUserResp
from hs5_api.models.remove_user_role_params import RemoveUserRoleParams
from hs5_api.models.remove_user_role_resp import RemoveUserRoleResp
from hs5_api.models.session_check_params import SessionCheckParams
from hs5_api.models.session_check_resp import SessionCheckResp

