# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class HapiError(BaseModel):
    """
    HapiError
    """ # noqa: E501
    herror: StrictStr
    msg: StrictStr
    __properties: ClassVar[List[str]] = ["herror", "msg"]

    @field_validator('herror')
    def herror_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['argon_encoding', 'user_already_exists', 'user_not_found', 'unknown_password_hashing', 'password_wrong', 'session_required', 'session_not_found', 'no_such_function', 'unexpected_continuation_token', 'bucket_not_found', 'error_starting_listing', 'invalid_path', 'error_listing_in_iteration', 'bucket_already_exists', 'invalid_parameters', 'internal_db_error', 'access_denied', 'error_deleting_object', 'error_deleting_bucket', 'invalid_policy_document', 'invalid_bucket_name']):
            raise ValueError("must be one of enum values ('argon_encoding', 'user_already_exists', 'user_not_found', 'unknown_password_hashing', 'password_wrong', 'session_required', 'session_not_found', 'no_such_function', 'unexpected_continuation_token', 'bucket_not_found', 'error_starting_listing', 'invalid_path', 'error_listing_in_iteration', 'bucket_already_exists', 'invalid_parameters', 'internal_db_error', 'access_denied', 'error_deleting_object', 'error_deleting_bucket', 'invalid_policy_document', 'invalid_bucket_name')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HapiError from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HapiError from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "herror": obj.get("herror"),
            "msg": obj.get("msg")
        })
        return _obj


