# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from hs5_api.models.list_bucket_permissions_resp_bucket_permissions_inner import ListBucketPermissionsRespBucketPermissionsInner
from typing import Optional, Set
from typing_extensions import Self

class ListBucketPermissionsResp(BaseModel):
    """
    ListBucketPermissionsResp
    """ # noqa: E501
    bucket_permissions: List[ListBucketPermissionsRespBucketPermissionsInner] = Field(alias="bucketPermissions")
    next_marker: StrictStr = Field(alias="nextMarker")
    is_truncated: StrictBool = Field(alias="isTruncated")
    __properties: ClassVar[List[str]] = ["bucketPermissions", "nextMarker", "isTruncated"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListBucketPermissionsResp from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bucket_permissions (list)
        _items = []
        if self.bucket_permissions:
            for _item_bucket_permissions in self.bucket_permissions:
                if _item_bucket_permissions:
                    _items.append(_item_bucket_permissions.to_dict())
            _dict['bucketPermissions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListBucketPermissionsResp from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bucketPermissions": [ListBucketPermissionsRespBucketPermissionsInner.from_dict(_item) for _item in obj["bucketPermissions"]] if obj.get("bucketPermissions") is not None else None,
            "nextMarker": obj.get("nextMarker"),
            "isTruncated": obj.get("isTruncated")
        })
        return _obj


