// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginData, LoginResponse, AddUserData, AddUserResponse, ListData, ListResponse, SessionCheckData, SessionCheckResponse, AddBucketData, AddBucketResponse, RemoveUserData, RemoveUserResponse, ListUsersData, ListUsersResponse, AddAccessKeyData, AddAccessKeyResponse, ListAccessKeysData, ListAccessKeysResponse, RemoveAccessKeyData, RemoveAccessKeyResponse, AddPolicyData, AddPolicyResponse, RemovePolicyData, RemovePolicyResponse, ListPoliciesData, ListPoliciesResponse, AddRoleData, AddRoleResponse, RemoveRoleData, RemoveRoleResponse, ListRolesData, ListRolesResponse, AddUserRoleData, AddUserRoleResponse, RemoveUserRoleData, RemoveUserRoleResponse, ListUserRolesData, ListUserRolesResponse, AddRolePolicyData, AddRolePolicyResponse, RemoveRolePolicyData, RemoveRolePolicyResponse, ListRolePoliciesData, ListRolePoliciesResponse, ChangePolicyData, ChangePolicyResponse, DeleteBucketData, DeleteBucketResponse, ChangePasswordData, ChangePasswordResponse, LogoutData, LogoutResponse } from './types.gen';

/**
 * Login with username and password to service
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const login = (data: LoginData = {}): CancelablePromise<LoginResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/login',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Adds a user
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const addUser = (data: AddUserData = {}): CancelablePromise<AddUserResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/addUser',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * List objects at location
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const list = (data: ListData = {}): CancelablePromise<ListResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/list',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Check if session is ok
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const sessionCheck = (data: SessionCheckData = {}): CancelablePromise<SessionCheckResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/sessionCheck',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Add new bucket
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const addBucket = (data: AddBucketData = {}): CancelablePromise<AddBucketResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/addBucket',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Remove a user
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const removeUser = (data: RemoveUserData = {}): CancelablePromise<RemoveUserResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/removeUser',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * List users
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const listUsers = (data: ListUsersData = {}): CancelablePromise<ListUsersResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/listUsers',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Add access key
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const addAccessKey = (data: AddAccessKeyData = {}): CancelablePromise<AddAccessKeyResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/addAccessKey',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * List access keys
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const listAccessKeys = (data: ListAccessKeysData = {}): CancelablePromise<ListAccessKeysResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/listAccessKeys',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Remove access key
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const removeAccessKey = (data: RemoveAccessKeyData = {}): CancelablePromise<RemoveAccessKeyResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/removeAccessKey',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Add policy
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const addPolicy = (data: AddPolicyData = {}): CancelablePromise<AddPolicyResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/addPolicy',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Remove policy
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const removePolicy = (data: RemovePolicyData = {}): CancelablePromise<RemovePolicyResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/removePolicy',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * List policies
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const listPolicies = (data: ListPoliciesData = {}): CancelablePromise<ListPoliciesResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/listPolicies',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Add role
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const addRole = (data: AddRoleData = {}): CancelablePromise<AddRoleResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/addRole',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Remove role
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const removeRole = (data: RemoveRoleData = {}): CancelablePromise<RemoveRoleResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/removeRole',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * List roles
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const listRoles = (data: ListRolesData = {}): CancelablePromise<ListRolesResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/listRoles',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Add user role
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const addUserRole = (data: AddUserRoleData = {}): CancelablePromise<AddUserRoleResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/addUserRole',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Remove user role
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const removeUserRole = (data: RemoveUserRoleData = {}): CancelablePromise<RemoveUserRoleResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/removeUserRole',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * List user roles
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const listUserRoles = (data: ListUserRolesData = {}): CancelablePromise<ListUserRolesResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/listUserRoles',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Add role policy
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const addRolePolicy = (data: AddRolePolicyData = {}): CancelablePromise<AddRolePolicyResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/addRolePolicy',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Remove role policy
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const removeRolePolicy = (data: RemoveRolePolicyData = {}): CancelablePromise<RemoveRolePolicyResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/removeRolePolicy',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * List role policies
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const listRolePolicies = (data: ListRolePoliciesData = {}): CancelablePromise<ListRolePoliciesResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/listRolePolicies',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Change policy
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const changePolicy = (data: ChangePolicyData = {}): CancelablePromise<ChangePolicyResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/changePolicy',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Delete bucket
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const deleteBucket = (data: DeleteBucketData = {}): CancelablePromise<DeleteBucketResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/deleteBucket',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Change password
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const changePassword = (data: ChangePasswordData = {}): CancelablePromise<ChangePasswordResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/changePassword',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Logout
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const logout = (data: LogoutData = {}): CancelablePromise<LogoutResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/logout',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};