// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { PostApiV1B64Be5124B034028A58913931942E205LoginData, PostApiV1B64Be5124B034028A58913931942E205LoginResponse, PostApiV1B64Be5124B034028A58913931942E205AddUserData, PostApiV1B64Be5124B034028A58913931942E205AddUserResponse, PostApiV1B64Be5124B034028A58913931942E205ListData, PostApiV1B64Be5124B034028A58913931942E205ListResponse, PostApiV1B64Be5124B034028A58913931942E205SessionCheckData, PostApiV1B64Be5124B034028A58913931942E205SessionCheckResponse, PostApiV1B64Be5124B034028A58913931942E205AddBucketData, PostApiV1B64Be5124B034028A58913931942E205AddBucketResponse } from './types.gen';

/**
 * Login with username and password to service
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const postApiV1B64Be5124B034028A58913931942E205Login = (data: PostApiV1B64Be5124B034028A58913931942E205LoginData = {}): CancelablePromise<PostApiV1B64Be5124B034028A58913931942E205LoginResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/login',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Adds a user
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const postApiV1B64Be5124B034028A58913931942E205AddUser = (data: PostApiV1B64Be5124B034028A58913931942E205AddUserData = {}): CancelablePromise<PostApiV1B64Be5124B034028A58913931942E205AddUserResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/addUser',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * List objects at location
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const postApiV1B64Be5124B034028A58913931942E205List = (data: PostApiV1B64Be5124B034028A58913931942E205ListData = {}): CancelablePromise<PostApiV1B64Be5124B034028A58913931942E205ListResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/list',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Check if session is ok
 * @param data The data for the request.
 * @param data.requestBody
 * @returns __paths__1api_v1_b64be512_4b03_4028_a589_13931942e205_1addBucket_post_responses_200_content_application_1json_schema OK
 * @throws ApiError
 */
export const postApiV1B64Be5124B034028A58913931942E205SessionCheck = (data: PostApiV1B64Be5124B034028A58913931942E205SessionCheckData = {}): CancelablePromise<PostApiV1B64Be5124B034028A58913931942E205SessionCheckResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/sessionCheck',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};

/**
 * Add new bucket
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const postApiV1B64Be5124B034028A58913931942E205AddBucket = (data: PostApiV1B64Be5124B034028A58913931942E205AddBucketData = {}): CancelablePromise<PostApiV1B64Be5124B034028A58913931942E205AddBucketResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/addBucket',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Error'
        }
    });
};