// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './models';

export class DefaultService {
	/**
	 * Login with username and password to service
	 * @returns any OK
	 * @throws ApiError
	 */
	public static postApiV1B64Be5124B034028A58913931942E205Login(data: $OpenApiTs['/api-v1-b64be512-4b03-4028-a589-13931942e205/login']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/api-v1-b64be512-4b03-4028-a589-13931942e205/login']['post']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'POST',
			url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/login',
			body: requestBody,
			mediaType: 'application/json',
			errors: {
				400: `Error`,
			},
		});
	}

	/**
	 * Adds a user
	 * @returns any OK
	 * @throws ApiError
	 */
	public static postApiV1B64Be5124B034028A58913931942E205Adduser(data: $OpenApiTs['/api-v1-b64be512-4b03-4028-a589-13931942e205/adduser']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/api-v1-b64be512-4b03-4028-a589-13931942e205/adduser']['post']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'POST',
			url: '/api-v1-b64be512-4b03-4028-a589-13931942e205/adduser',
			body: requestBody,
			mediaType: 'application/json',
			errors: {
				400: `Error`,
			},
		});
	}

}