// This file is auto-generated by @hey-api/openapi-ts

export type PostApiV1B64Be5124B034028A58913931942E205LoginData = {
    requestBody?: {
        username: string;
        password: string;
    };
};

export type PostApiV1B64Be5124B034028A58913931942E205LoginResponse = ({
    ses: string;
    accessKey: string;
    secretAccessKey: string;
});

export type PostApiV1B64Be5124B034028A58913931942E205AddUserData = {
    requestBody?: {
        ses: string;
        username: string;
        password: string;
    };
};

export type PostApiV1B64Be5124B034028A58913931942E205AddUserResponse = ({
    dummy?: string;
});

export type PostApiV1B64Be5124B034028A58913931942E205ListData = {
    requestBody?: {
        ses: string;
        path: string;
        continuationToken?: string;
    };
};

export type PostApiV1B64Be5124B034028A58913931942E205ListResponse = ({
    objects: Array<{
        type: 0 | 1 | 2;
        name: string;
        size?: number;
    }>;
    nextMarker: string;
    isTruncated: boolean;
});

export type PostApiV1B64Be5124B034028A58913931942E205SessionCheckData = {
    requestBody?: {
        ses: string;
    };
};

export type PostApiV1B64Be5124B034028A58913931942E205SessionCheckResponse = ({
    dummy?: string;
});

export type PostApiV1B64Be5124B034028A58913931942E205AddBucketData = {
    requestBody?: {
        ses: string;
        bucketName: string;
    };
};

export type PostApiV1B64Be5124B034028A58913931942E205AddBucketResponse = ({
    dummy?: string;
});