// This file is auto-generated by @hey-api/openapi-ts

export type LoginData = {
    requestBody?: {
        username: string;
        password: string;
    };
};

export type LoginResponse = ({
    ses: string;
    accessKey: string;
    secretAccessKey: string;
});

export type AddUserData = {
    requestBody?: {
        username: string;
        password: string;
    };
};

export type AddUserResponse = ({
    id: string;
});

export type ListData = {
    requestBody?: {
        path: string;
        continuationToken?: string;
    };
};

export type ListResponse = ({
    objects: Array<{
        type: 0 | 1 | 2;
        name: string;
        size: number;
        lastModified: number;
        created: number;
    }>;
    nextMarker: string;
    isTruncated: boolean;
});

export type SessionCheckData = {
    requestBody?: {
        dummy?: string;
    };
};

export type SessionCheckResponse = ({
    dummy?: string;
});

export type AddBucketData = {
    requestBody?: {
        bucketName: string;
    };
};

export type AddBucketResponse = ({
    dummy?: string;
});

export type RemoveUserData = {
    requestBody?: {
        username: string;
    };
};

export type RemoveUserResponse = ({
    dummy?: string;
});

export type ListUsersData = {
    requestBody?: {
        continuationToken?: string;
    };
};

export type ListUsersResponse = ({
    users: Array<{
        username: string;
        id: string;
        system: boolean;
    }>;
    nextMarker: string;
    isTruncated: boolean;
});

export type AddAccessKeyData = {
    requestBody?: {
        userId: string;
    };
};

export type AddAccessKeyResponse = ({
    id: string;
    accessKey: string;
    secretKey: string;
});

export type ListAccessKeysData = {
    requestBody?: {
        userId: string;
        continuationToken?: string;
    };
};

export type ListAccessKeysResponse = ({
    accessKeys: Array<{
        id: string;
        accessKeyId: string;
    }>;
    nextMarker: string;
    isTruncated: boolean;
});

export type RemoveAccessKeyData = {
    requestBody?: {
        id: string;
    };
};

export type RemoveAccessKeyResponse = ({
    dummy?: string;
});

export type AddPolicyData = {
    requestBody?: {
        policyName: string;
        policyDocument: string;
    };
};

export type AddPolicyResponse = ({
    id: string;
});

export type RemovePolicyData = {
    requestBody?: {
        id: string;
    };
};

export type RemovePolicyResponse = ({
    dummy?: string;
});

export type ListPoliciesData = {
    requestBody?: {
        continuationToken?: string;
    };
};

export type ListPoliciesResponse = ({
    policies: Array<{
        id: string;
        name: string;
        document: string;
        system: boolean;
    }>;
    nextMarker: string;
    isTruncated: boolean;
});

export type AddRoleData = {
    requestBody?: {
        roleName: string;
    };
};

export type AddRoleResponse = ({
    id: string;
});

export type RemoveRoleData = {
    requestBody?: {
        id: string;
    };
};

export type RemoveRoleResponse = ({
    dummy?: string;
});

export type ListRolesData = {
    requestBody?: {
        continuationToken?: string;
    };
};

export type ListRolesResponse = ({
    roles: Array<{
        id: string;
        roleName: string;
        system: boolean;
    }>;
    nextMarker: string;
    isTruncated: boolean;
});

export type AddUserRoleData = {
    requestBody?: {
        userId: string;
        roleId: string;
    };
};

export type AddUserRoleResponse = ({
    dummy?: string;
});

export type RemoveUserRoleData = {
    requestBody?: {
        id: string;
    };
};

export type RemoveUserRoleResponse = ({
    dummy?: string;
});

export type ListUserRolesData = {
    requestBody?: {
        userId: string;
        continuationToken?: string;
    };
};

export type ListUserRolesResponse = ({
    userRoles: Array<{
        id: string;
        roleId: string;
        roleName: string;
        system: boolean;
    }>;
    nextMarker: string;
    isTruncated: boolean;
});

export type AddRolePolicyData = {
    requestBody?: {
        roleId: string;
        policyId: string;
    };
};

export type AddRolePolicyResponse = ({
    dummy?: string;
});

export type RemoveRolePolicyData = {
    requestBody?: {
        id: string;
    };
};

export type RemoveRolePolicyResponse = ({
    dummy?: string;
});

export type ListRolePoliciesData = {
    requestBody?: {
        roleId: string;
        continuationToken?: string;
    };
};

export type ListRolePoliciesResponse = ({
    rolePolicies: Array<{
        id: string;
        policyId: string;
        policyName: string;
        system: boolean;
    }>;
    nextMarker: string;
    isTruncated: boolean;
});

export type ChangePolicyData = {
    requestBody?: {
        id: string;
        document: string;
    };
};

export type ChangePolicyResponse = ({
    dummy?: string;
});

export type DeleteBucketData = {
    requestBody?: {
        bucketName: string;
    };
};

export type DeleteBucketResponse = ({
    dummy?: string;
});

export type ChangePasswordData = {
    requestBody?: {
        oldPassword: string;
        password: string;
    };
};

export type ChangePasswordResponse = ({
    dummy?: string;
});

export type LogoutData = {
    requestBody?: {
        dummy?: string;
    };
};

export type LogoutResponse = ({
    dummy?: string;
});