# coding: utf-8

# flake8: noqa

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddAccessKeyParams",
    "AddAccessKeyResp",
    "AddBucketParams",
    "AddBucketPermissionParams",
    "AddBucketPermissionResp",
    "AddBucketResp",
    "AddPolicyParams",
    "AddPolicyResp",
    "AddRoleParams",
    "AddRolePolicyParams",
    "AddRolePolicyResp",
    "AddRoleResp",
    "AddUserParams",
    "AddUserResp",
    "AddUserRoleParams",
    "AddUserRoleResp",
    "ChangePasswordParams",
    "ChangePasswordResp",
    "ChangePolicyParams",
    "ChangePolicyResp",
    "DeleteBucketParams",
    "DeleteBucketResp",
    "HapiError",
    "ListAccessKeysParams",
    "ListAccessKeysResp",
    "ListAccessKeysRespAccessKeysInner",
    "ListBucketPermissionsParams",
    "ListBucketPermissionsResp",
    "ListBucketPermissionsRespBucketPermissionsInner",
    "ListParams",
    "ListPoliciesParams",
    "ListPoliciesResp",
    "ListPoliciesRespPoliciesInner",
    "ListResp",
    "ListRespObjectsInner",
    "ListRolePoliciesParams",
    "ListRolePoliciesResp",
    "ListRolePoliciesRespRolePoliciesInner",
    "ListRolesParams",
    "ListRolesResp",
    "ListRolesRespRolesInner",
    "ListUserRolesParams",
    "ListUserRolesResp",
    "ListUserRolesRespUserRolesInner",
    "ListUsersParams",
    "ListUsersResp",
    "ListUsersRespUsersInner",
    "LoginParams",
    "LoginResp",
    "LogoutParams",
    "LogoutResp",
    "RemoveAccessKeyParams",
    "RemoveAccessKeyResp",
    "RemoveBucketPermissionParams",
    "RemoveBucketPermissionResp",
    "RemovePolicyParams",
    "RemovePolicyResp",
    "RemoveRoleParams",
    "RemoveRolePolicyParams",
    "RemoveRolePolicyResp",
    "RemoveRoleResp",
    "RemoveUserParams",
    "RemoveUserResp",
    "RemoveUserRoleParams",
    "RemoveUserRoleResp",
    "SessionCheckParams",
    "SessionCheckResp",
]

# import apis into sdk package
from hs5_api.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from hs5_api.api_response import ApiResponse as ApiResponse
from hs5_api.api_client import ApiClient as ApiClient
from hs5_api.configuration import Configuration as Configuration
from hs5_api.exceptions import OpenApiException as OpenApiException
from hs5_api.exceptions import ApiTypeError as ApiTypeError
from hs5_api.exceptions import ApiValueError as ApiValueError
from hs5_api.exceptions import ApiKeyError as ApiKeyError
from hs5_api.exceptions import ApiAttributeError as ApiAttributeError
from hs5_api.exceptions import ApiException as ApiException

# import models into sdk package
from hs5_api.models.add_access_key_params import AddAccessKeyParams as AddAccessKeyParams
from hs5_api.models.add_access_key_resp import AddAccessKeyResp as AddAccessKeyResp
from hs5_api.models.add_bucket_params import AddBucketParams as AddBucketParams
from hs5_api.models.add_bucket_permission_params import AddBucketPermissionParams as AddBucketPermissionParams
from hs5_api.models.add_bucket_permission_resp import AddBucketPermissionResp as AddBucketPermissionResp
from hs5_api.models.add_bucket_resp import AddBucketResp as AddBucketResp
from hs5_api.models.add_policy_params import AddPolicyParams as AddPolicyParams
from hs5_api.models.add_policy_resp import AddPolicyResp as AddPolicyResp
from hs5_api.models.add_role_params import AddRoleParams as AddRoleParams
from hs5_api.models.add_role_policy_params import AddRolePolicyParams as AddRolePolicyParams
from hs5_api.models.add_role_policy_resp import AddRolePolicyResp as AddRolePolicyResp
from hs5_api.models.add_role_resp import AddRoleResp as AddRoleResp
from hs5_api.models.add_user_params import AddUserParams as AddUserParams
from hs5_api.models.add_user_resp import AddUserResp as AddUserResp
from hs5_api.models.add_user_role_params import AddUserRoleParams as AddUserRoleParams
from hs5_api.models.add_user_role_resp import AddUserRoleResp as AddUserRoleResp
from hs5_api.models.change_password_params import ChangePasswordParams as ChangePasswordParams
from hs5_api.models.change_password_resp import ChangePasswordResp as ChangePasswordResp
from hs5_api.models.change_policy_params import ChangePolicyParams as ChangePolicyParams
from hs5_api.models.change_policy_resp import ChangePolicyResp as ChangePolicyResp
from hs5_api.models.delete_bucket_params import DeleteBucketParams as DeleteBucketParams
from hs5_api.models.delete_bucket_resp import DeleteBucketResp as DeleteBucketResp
from hs5_api.models.hapi_error import HapiError as HapiError
from hs5_api.models.list_access_keys_params import ListAccessKeysParams as ListAccessKeysParams
from hs5_api.models.list_access_keys_resp import ListAccessKeysResp as ListAccessKeysResp
from hs5_api.models.list_access_keys_resp_access_keys_inner import ListAccessKeysRespAccessKeysInner as ListAccessKeysRespAccessKeysInner
from hs5_api.models.list_bucket_permissions_params import ListBucketPermissionsParams as ListBucketPermissionsParams
from hs5_api.models.list_bucket_permissions_resp import ListBucketPermissionsResp as ListBucketPermissionsResp
from hs5_api.models.list_bucket_permissions_resp_bucket_permissions_inner import ListBucketPermissionsRespBucketPermissionsInner as ListBucketPermissionsRespBucketPermissionsInner
from hs5_api.models.list_params import ListParams as ListParams
from hs5_api.models.list_policies_params import ListPoliciesParams as ListPoliciesParams
from hs5_api.models.list_policies_resp import ListPoliciesResp as ListPoliciesResp
from hs5_api.models.list_policies_resp_policies_inner import ListPoliciesRespPoliciesInner as ListPoliciesRespPoliciesInner
from hs5_api.models.list_resp import ListResp as ListResp
from hs5_api.models.list_resp_objects_inner import ListRespObjectsInner as ListRespObjectsInner
from hs5_api.models.list_role_policies_params import ListRolePoliciesParams as ListRolePoliciesParams
from hs5_api.models.list_role_policies_resp import ListRolePoliciesResp as ListRolePoliciesResp
from hs5_api.models.list_role_policies_resp_role_policies_inner import ListRolePoliciesRespRolePoliciesInner as ListRolePoliciesRespRolePoliciesInner
from hs5_api.models.list_roles_params import ListRolesParams as ListRolesParams
from hs5_api.models.list_roles_resp import ListRolesResp as ListRolesResp
from hs5_api.models.list_roles_resp_roles_inner import ListRolesRespRolesInner as ListRolesRespRolesInner
from hs5_api.models.list_user_roles_params import ListUserRolesParams as ListUserRolesParams
from hs5_api.models.list_user_roles_resp import ListUserRolesResp as ListUserRolesResp
from hs5_api.models.list_user_roles_resp_user_roles_inner import ListUserRolesRespUserRolesInner as ListUserRolesRespUserRolesInner
from hs5_api.models.list_users_params import ListUsersParams as ListUsersParams
from hs5_api.models.list_users_resp import ListUsersResp as ListUsersResp
from hs5_api.models.list_users_resp_users_inner import ListUsersRespUsersInner as ListUsersRespUsersInner
from hs5_api.models.login_params import LoginParams as LoginParams
from hs5_api.models.login_resp import LoginResp as LoginResp
from hs5_api.models.logout_params import LogoutParams as LogoutParams
from hs5_api.models.logout_resp import LogoutResp as LogoutResp
from hs5_api.models.remove_access_key_params import RemoveAccessKeyParams as RemoveAccessKeyParams
from hs5_api.models.remove_access_key_resp import RemoveAccessKeyResp as RemoveAccessKeyResp
from hs5_api.models.remove_bucket_permission_params import RemoveBucketPermissionParams as RemoveBucketPermissionParams
from hs5_api.models.remove_bucket_permission_resp import RemoveBucketPermissionResp as RemoveBucketPermissionResp
from hs5_api.models.remove_policy_params import RemovePolicyParams as RemovePolicyParams
from hs5_api.models.remove_policy_resp import RemovePolicyResp as RemovePolicyResp
from hs5_api.models.remove_role_params import RemoveRoleParams as RemoveRoleParams
from hs5_api.models.remove_role_policy_params import RemoveRolePolicyParams as RemoveRolePolicyParams
from hs5_api.models.remove_role_policy_resp import RemoveRolePolicyResp as RemoveRolePolicyResp
from hs5_api.models.remove_role_resp import RemoveRoleResp as RemoveRoleResp
from hs5_api.models.remove_user_params import RemoveUserParams as RemoveUserParams
from hs5_api.models.remove_user_resp import RemoveUserResp as RemoveUserResp
from hs5_api.models.remove_user_role_params import RemoveUserRoleParams as RemoveUserRoleParams
from hs5_api.models.remove_user_role_resp import RemoveUserRoleResp as RemoveUserRoleResp
from hs5_api.models.session_check_params import SessionCheckParams as SessionCheckParams
from hs5_api.models.session_check_resp import SessionCheckResp as SessionCheckResp

