name: HS5 jekyll site
pygments: false
encoding: UTF-8
curr_version: 0.1
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"