# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.list_user_roles_resp_user_roles_inner import ListUserRolesRespUserRolesInner

class TestListUserRolesRespUserRolesInner(unittest.TestCase):
    """ListUserRolesRespUserRolesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListUserRolesRespUserRolesInner:
        """Test ListUserRolesRespUserRolesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListUserRolesRespUserRolesInner`
        """
        model = ListUserRolesRespUserRolesInner()
        if include_optional:
            return ListUserRolesRespUserRolesInner(
                id = '',
                role_id = '',
                role_name = '',
                system = True
            )
        else:
            return ListUserRolesRespUserRolesInner(
                id = '',
                role_id = '',
                role_name = '',
                system = True,
        )
        """

    def testListUserRolesRespUserRolesInner(self):
        """Test ListUserRolesRespUserRolesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
