# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.remove_user_params import RemoveUserParams

class TestRemoveUserParams(unittest.TestCase):
    """RemoveUserParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemoveUserParams:
        """Test RemoveUserParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemoveUserParams`
        """
        model = RemoveUserParams()
        if include_optional:
            return RemoveUserParams(
                ses = '',
                username = ''
            )
        else:
            return RemoveUserParams(
                ses = '',
                username = '',
        )
        """

    def testRemoveUserParams(self):
        """Test RemoveUserParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
