# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.remove_access_key_resp import RemoveAccessKeyResp

class TestRemoveAccessKeyResp(unittest.TestCase):
    """RemoveAccessKeyResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemoveAccessKeyResp:
        """Test RemoveAccessKeyResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemoveAccessKeyResp`
        """
        model = RemoveAccessKeyResp()
        if include_optional:
            return RemoveAccessKeyResp(
                dummy = ''
            )
        else:
            return RemoveAccessKeyResp(
        )
        """

    def testRemoveAccessKeyResp(self):
        """Test RemoveAccessKeyResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
