# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.list_users_resp_users_inner import ListUsersRespUsersInner

class TestListUsersRespUsersInner(unittest.TestCase):
    """ListUsersRespUsersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListUsersRespUsersInner:
        """Test ListUsersRespUsersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListUsersRespUsersInner`
        """
        model = ListUsersRespUsersInner()
        if include_optional:
            return ListUsersRespUsersInner(
                username = '',
                id = '',
                system = True
            )
        else:
            return ListUsersRespUsersInner(
                username = '',
                id = '',
                system = True,
        )
        """

    def testListUsersRespUsersInner(self):
        """Test ListUsersRespUsersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
