# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.list_policies_resp import ListPoliciesResp

class TestListPoliciesResp(unittest.TestCase):
    """ListPoliciesResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListPoliciesResp:
        """Test ListPoliciesResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListPoliciesResp`
        """
        model = ListPoliciesResp()
        if include_optional:
            return ListPoliciesResp(
                policies = [
                    hs5_api.models.list_policies_resp_policies_inner.ListPoliciesResp_policies_inner(
                        id = '', 
                        name = '', 
                        document = '', 
                        system = True, )
                    ],
                next_marker = '',
                is_truncated = True
            )
        else:
            return ListPoliciesResp(
                policies = [
                    hs5_api.models.list_policies_resp_policies_inner.ListPoliciesResp_policies_inner(
                        id = '', 
                        name = '', 
                        document = '', 
                        system = True, )
                    ],
                next_marker = '',
                is_truncated = True,
        )
        """

    def testListPoliciesResp(self):
        """Test ListPoliciesResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
