# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.list_user_roles_resp import ListUserRolesResp

class TestListUserRolesResp(unittest.TestCase):
    """ListUserRolesResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListUserRolesResp:
        """Test ListUserRolesResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListUserRolesResp`
        """
        model = ListUserRolesResp()
        if include_optional:
            return ListUserRolesResp(
                user_roles = [
                    hs5_api.models.list_user_roles_resp_user_roles_inner.ListUserRolesResp_userRoles_inner(
                        id = '', 
                        role_id = '', 
                        role_name = '', 
                        system = True, )
                    ],
                next_marker = '',
                is_truncated = True
            )
        else:
            return ListUserRolesResp(
                user_roles = [
                    hs5_api.models.list_user_roles_resp_user_roles_inner.ListUserRolesResp_userRoles_inner(
                        id = '', 
                        role_id = '', 
                        role_name = '', 
                        system = True, )
                    ],
                next_marker = '',
                is_truncated = True,
        )
        """

    def testListUserRolesResp(self):
        """Test ListUserRolesResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
