# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.list_bucket_permissions_resp import ListBucketPermissionsResp

class TestListBucketPermissionsResp(unittest.TestCase):
    """ListBucketPermissionsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListBucketPermissionsResp:
        """Test ListBucketPermissionsResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListBucketPermissionsResp`
        """
        model = ListBucketPermissionsResp()
        if include_optional:
            return ListBucketPermissionsResp(
                bucket_permissions = [
                    hs5_api.models.list_bucket_permissions_resp_bucket_permissions_inner.ListBucketPermissionsResp_bucketPermissions_inner(
                        id = '', 
                        user_id = '', 
                        user_name = '', 
                        permissions = [
                            'read'
                            ], )
                    ],
                next_marker = '',
                is_truncated = True
            )
        else:
            return ListBucketPermissionsResp(
                bucket_permissions = [
                    hs5_api.models.list_bucket_permissions_resp_bucket_permissions_inner.ListBucketPermissionsResp_bucketPermissions_inner(
                        id = '', 
                        user_id = '', 
                        user_name = '', 
                        permissions = [
                            'read'
                            ], )
                    ],
                next_marker = '',
                is_truncated = True,
        )
        """

    def testListBucketPermissionsResp(self):
        """Test ListBucketPermissionsResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
