# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.add_bucket_permission_params import AddBucketPermissionParams

class TestAddBucketPermissionParams(unittest.TestCase):
    """AddBucketPermissionParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddBucketPermissionParams:
        """Test AddBucketPermissionParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddBucketPermissionParams`
        """
        model = AddBucketPermissionParams()
        if include_optional:
            return AddBucketPermissionParams(
                user_id = '',
                bucket_name = '',
                add_bucket_permissions = [
                    'read'
                    ]
            )
        else:
            return AddBucketPermissionParams(
                user_id = '',
                bucket_name = '',
                add_bucket_permissions = [
                    'read'
                    ],
        )
        """

    def testAddBucketPermissionParams(self):
        """Test AddBucketPermissionParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
