# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_add_access_key_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_add_access_key_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_add_bucket_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_add_bucket_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_add_policy_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_add_policy_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_add_role_policy_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_add_role_policy_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_add_role_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_add_role_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_add_user_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_add_user_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_add_user_role_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_add_user_role_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_change_password_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_change_password_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_change_policy_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_change_policy_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_delete_bucket_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_delete_bucket_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_list_access_keys_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_list_access_keys_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_list_policies_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_list_policies_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_list_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_list_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_list_role_policies_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_list_role_policies_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_list_roles_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_list_roles_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_list_user_roles_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_list_user_roles_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_list_users_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_list_users_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_login_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_login_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_logout_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_logout_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_remove_access_key_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_remove_access_key_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_remove_policy_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_remove_policy_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_remove_role_policy_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_remove_role_policy_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_remove_role_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_remove_role_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_remove_user_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_remove_user_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_remove_user_role_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_remove_user_role_post

        """
        pass

    def test_api_v1_b64be5124b034028_a58913931942e205_session_check_post(self) -> None:
        """Test case for api_v1_b64be5124b034028_a58913931942e205_session_check_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
