# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.add_access_key_resp import AddAccessKeyResp

class TestAddAccessKeyResp(unittest.TestCase):
    """AddAccessKeyResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddAccessKeyResp:
        """Test AddAccessKeyResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddAccessKeyResp`
        """
        model = AddAccessKeyResp()
        if include_optional:
            return AddAccessKeyResp(
                id = '',
                access_key = '',
                secret_key = ''
            )
        else:
            return AddAccessKeyResp(
                id = '',
                access_key = '',
                secret_key = '',
        )
        """

    def testAddAccessKeyResp(self):
        """Test AddAccessKeyResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
