# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.add_policy_params import AddPolicyParams

class TestAddPolicyParams(unittest.TestCase):
    """AddPolicyParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddPolicyParams:
        """Test AddPolicyParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddPolicyParams`
        """
        model = AddPolicyParams()
        if include_optional:
            return AddPolicyParams(
                ses = '',
                policy_name = '',
                policy_document = ''
            )
        else:
            return AddPolicyParams(
                ses = '',
                policy_name = '',
                policy_document = '',
        )
        """

    def testAddPolicyParams(self):
        """Test AddPolicyParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
