# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.remove_role_policy_resp import RemoveRolePolicyResp

class TestRemoveRolePolicyResp(unittest.TestCase):
    """RemoveRolePolicyResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemoveRolePolicyResp:
        """Test RemoveRolePolicyResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemoveRolePolicyResp`
        """
        model = RemoveRolePolicyResp()
        if include_optional:
            return RemoveRolePolicyResp(
                dummy = ''
            )
        else:
            return RemoveRolePolicyResp(
        )
        """

    def testRemoveRolePolicyResp(self):
        """Test RemoveRolePolicyResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
