# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.list_access_keys_resp import ListAccessKeysResp

class TestListAccessKeysResp(unittest.TestCase):
    """ListAccessKeysResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAccessKeysResp:
        """Test ListAccessKeysResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAccessKeysResp`
        """
        model = ListAccessKeysResp()
        if include_optional:
            return ListAccessKeysResp(
                access_keys = [
                    hs5_api.models.list_access_keys_resp_access_keys_inner.ListAccessKeysResp_accessKeys_inner(
                        id = '', 
                        access_key_id = '', )
                    ],
                next_marker = '',
                is_truncated = True
            )
        else:
            return ListAccessKeysResp(
                access_keys = [
                    hs5_api.models.list_access_keys_resp_access_keys_inner.ListAccessKeysResp_accessKeys_inner(
                        id = '', 
                        access_key_id = '', )
                    ],
                next_marker = '',
                is_truncated = True,
        )
        """

    def testListAccessKeysResp(self):
        """Test ListAccessKeysResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
