# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.add_role_policy_resp import AddRolePolicyResp

class TestAddRolePolicyResp(unittest.TestCase):
    """AddRolePolicyResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddRolePolicyResp:
        """Test AddRolePolicyResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddRolePolicyResp`
        """
        model = AddRolePolicyResp()
        if include_optional:
            return AddRolePolicyResp(
                dummy = ''
            )
        else:
            return AddRolePolicyResp(
        )
        """

    def testAddRolePolicyResp(self):
        """Test AddRolePolicyResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
