# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.list_roles_resp import ListRolesResp

class TestListRolesResp(unittest.TestCase):
    """ListRolesResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListRolesResp:
        """Test ListRolesResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListRolesResp`
        """
        model = ListRolesResp()
        if include_optional:
            return ListRolesResp(
                roles = [
                    hs5_api.models.list_roles_resp_roles_inner.ListRolesResp_roles_inner(
                        id = '', 
                        role_name = '', 
                        system = True, )
                    ],
                next_marker = '',
                is_truncated = True
            )
        else:
            return ListRolesResp(
                roles = [
                    hs5_api.models.list_roles_resp_roles_inner.ListRolesResp_roles_inner(
                        id = '', 
                        role_name = '', 
                        system = True, )
                    ],
                next_marker = '',
                is_truncated = True,
        )
        """

    def testListRolesResp(self):
        """Test ListRolesResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
