# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.list_bucket_permissions_resp_bucket_permissions_inner import ListBucketPermissionsRespBucketPermissionsInner

class TestListBucketPermissionsRespBucketPermissionsInner(unittest.TestCase):
    """ListBucketPermissionsRespBucketPermissionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListBucketPermissionsRespBucketPermissionsInner:
        """Test ListBucketPermissionsRespBucketPermissionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListBucketPermissionsRespBucketPermissionsInner`
        """
        model = ListBucketPermissionsRespBucketPermissionsInner()
        if include_optional:
            return ListBucketPermissionsRespBucketPermissionsInner(
                id = '',
                user_id = '',
                user_name = '',
                permissions = [
                    'read'
                    ]
            )
        else:
            return ListBucketPermissionsRespBucketPermissionsInner(
                id = '',
                user_id = '',
                user_name = '',
                permissions = [
                    'read'
                    ],
        )
        """

    def testListBucketPermissionsRespBucketPermissionsInner(self):
        """Test ListBucketPermissionsRespBucketPermissionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
