# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.remove_user_role_params import RemoveUserRoleParams

class TestRemoveUserRoleParams(unittest.TestCase):
    """RemoveUserRoleParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemoveUserRoleParams:
        """Test RemoveUserRoleParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemoveUserRoleParams`
        """
        model = RemoveUserRoleParams()
        if include_optional:
            return RemoveUserRoleParams(
                ses = '',
                id = ''
            )
        else:
            return RemoveUserRoleParams(
                ses = '',
                id = '',
        )
        """

    def testRemoveUserRoleParams(self):
        """Test RemoveUserRoleParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
