# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.list_role_policies_resp_role_policies_inner import ListRolePoliciesRespRolePoliciesInner

class TestListRolePoliciesRespRolePoliciesInner(unittest.TestCase):
    """ListRolePoliciesRespRolePoliciesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListRolePoliciesRespRolePoliciesInner:
        """Test ListRolePoliciesRespRolePoliciesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListRolePoliciesRespRolePoliciesInner`
        """
        model = ListRolePoliciesRespRolePoliciesInner()
        if include_optional:
            return ListRolePoliciesRespRolePoliciesInner(
                id = '',
                policy_id = '',
                policy_name = '',
                system = True
            )
        else:
            return ListRolePoliciesRespRolePoliciesInner(
                id = '',
                policy_id = '',
                policy_name = '',
                system = True,
        )
        """

    def testListRolePoliciesRespRolePoliciesInner(self):
        """Test ListRolePoliciesRespRolePoliciesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
