# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.list_role_policies_params import ListRolePoliciesParams

class TestListRolePoliciesParams(unittest.TestCase):
    """ListRolePoliciesParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListRolePoliciesParams:
        """Test ListRolePoliciesParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListRolePoliciesParams`
        """
        model = ListRolePoliciesParams()
        if include_optional:
            return ListRolePoliciesParams(
                ses = '',
                role_id = '',
                continuation_token = ''
            )
        else:
            return ListRolePoliciesParams(
                ses = '',
                role_id = '',
        )
        """

    def testListRolePoliciesParams(self):
        """Test ListRolePoliciesParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
