# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.list_resp import ListResp

class TestListResp(unittest.TestCase):
    """ListResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListResp:
        """Test ListResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListResp`
        """
        model = ListResp()
        if include_optional:
            return ListResp(
                objects = [
                    hs5_api.models.list_resp_objects_inner.ListResp_objects_inner(
                        type = 0, 
                        name = '', 
                        size = 56, 
                        last_modified = 56, 
                        created = 56, )
                    ],
                next_marker = '',
                is_truncated = True
            )
        else:
            return ListResp(
                objects = [
                    hs5_api.models.list_resp_objects_inner.ListResp_objects_inner(
                        type = 0, 
                        name = '', 
                        size = 56, 
                        last_modified = 56, 
                        created = 56, )
                    ],
                next_marker = '',
                is_truncated = True,
        )
        """

    def testListResp(self):
        """Test ListResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
