# coding: utf-8

"""
    HS5 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hs5_api.models.remove_policy_params import RemovePolicyParams

class TestRemovePolicyParams(unittest.TestCase):
    """RemovePolicyParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemovePolicyParams:
        """Test RemovePolicyParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemovePolicyParams`
        """
        model = RemovePolicyParams()
        if include_optional:
            return RemovePolicyParams(
                ses = '',
                id = ''
            )
        else:
            return RemovePolicyParams(
                ses = '',
                id = '',
        )
        """

    def testRemovePolicyParams(self):
        """Test RemovePolicyParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
