openapi: '3.0.2'
info:
  title: HS5 API
  version: '1.0'
paths:
  /api-v1-b64be512-4b03-4028-a589-13931942e205/login:
    post:
      description: Login with username and password to service
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/LoginParams.json'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'schemas/LoginResp.json'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: 'schemas/HapiError.json'
  /api-v1-b64be512-4b03-4028-a589-13931942e205/adduser:
    post:
      description: Adds a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/AddUserParams.json'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'schemas/AddUserResp.json'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: 'schemas/HapiError.json'
  /api-v1-b64be512-4b03-4028-a589-13931942e205/list:
    post:
      description: List objects at location
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/ListParams.json'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'schemas/ListResp.json'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: 'schemas/HapiError.json'